public class mathoperationsutility 
{
    public static integer addition(integer x , integer y)
    {
        return x+y;
    }
    public static boolean checkequals(integer x,integer y)
    {
        if (x==y)
            return true;
        else 
            return false;
    }
    public static integer bignumber(integer x , integer y)
    {
        if (x>y)
            return x;
        else 
            return y;
    }

}