public class mathoperationshelper 
{
    public static  void addition(integer x,integer y)
    {
        system.debug('addition result is ...' + (x+y));
    }
    public static void subtraction(integer x,integer y)
    {
        system.debug('subtraction result is ...' + (x-y));
    }
    public static void multiplication(integer x,integer y)
    {
        system.debug('multiplication result is ...' + (x*y));
    }
    public static void division(integer x,integer y)
    {
        system.debug('division result is ...' + (x/y));
    }
    public static void mod(integer x,integer y)
    {
        system.debug('division result is ...' + (y/x));
    }
        

}